# Default values for dotnet-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: moreirajr/sample-dotnet-api
  pullPolicy: IfNotPresent
  tag: 1.0.1

service:
  type: NodePort # ClusterIp | NodePort | LoadBalancer
  port: 8080
  targetPort: 5000

app:
  version: 1.0.0

ingress:
  host: dotnet-api.local